import { MetadataRoute } from "next";

export default function sitemap(): MetadataRoute.Sitemap {
  return [
    {
      url: "https://www.hormoscale.com",
      lastModified: new Date(),
      changeFrequency: "daily",
      priority: 1,
    },
    {
      url: "https://www.hormoscale.com/disclaimer",
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.5,
    },
    {
      url: "https://www.hormoscale.com/ozempic-weight-loss-calculator",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.hormoscale.com/wegovy-weight-loss-calculator",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.hormoscale.com/mounjaro-weight-loss-calculator",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.hormoscale.com/semaglutide-weight-loss-calculator",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.hormoscale.com/tirzepatide-weight-loss-calculator",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.hormoscale.com/wegovy-vs-ozempic",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://www.hormoscale.com/mounjaro-vs-wegovy",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://www.hormoscale.com/tirzepatide-vs-semaglutide",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://www.hormoscale.com/blog",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://www.hormoscale.com/blog/ozempic-weight-loss-timeline",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.75,
    },
    {
      url: "https://www.hormoscale.com/blog/how-long-does-wegovy-take-to-work",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.75,
    },
    {
      url: "https://www.hormoscale.com/blog/mounjaro-vs-ozempic-side-effects",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.75,
    },
    {
      url: "https://www.hormoscale.com/blog/what-bmi-qualifies-for-wegovy",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.75,
    },
    {
      url: "https://www.hormoscale.com/blog/semaglutide-meal-plan",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.75,
    },
    {
      url: "https://www.hormoscale.com/blog/tirzepatide-weight-loss-timeline",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.75,
    },
    {
      url: "https://www.hormoscale.com/blog/ozempic-side-effects",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.75,
    },
    {
      url: "https://www.hormoscale.com/blog/wegovy-dosage-guide",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.75,
    },
    {
      url: "https://www.hormoscale.com/blog/mounjaro-vs-ozempic-weight-loss",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.75,
    },
    {
      url: "https://www.hormoscale.com/blog/tirzepatide-cost-comparison",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.75,
    },
    {
      url: "https://www.hormoscale.com/blog/glp1-weight-loss-plateau",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.75,
    },
    {
      url: "https://www.hormoscale.com/blog/best-glp1-for-weight-loss",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.75,
    },
    {
      url: "https://www.hormoscale.com/blog/how-glp1-medications-work",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.75,
    },
    {
      url: "https://www.hormoscale.com/blog/wegovy-vs-zepbound",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.75,
    },
    {
      url: "https://www.hormoscale.com/blog/ozempic-vs-semaglutide",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.75,
    },
    {
      url: "https://www.hormoscale.com/blog/mounjaro-side-effects",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.75,
    },
    {
      url: "https://www.hormoscale.com/blog/glp1-before-and-after-expectations",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.75,
    },
    {
      url: "https://www.hormoscale.com/blog/weight-loss-bmi-guide",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.75,
    },
    {
      url: "https://www.hormoscale.com/blog/glp1-appetite-control",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.75,
    },
    {
      url: "https://www.hormoscale.com/blog/tirzepatide-vs-semaglutide",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.75,
    },
  ];
}